baseURL = "https://www.kitamstudios.com/"
languageCode = "en-us"
title = "Kitam Studios"
theme = "minimal"
disqusShortname = "kitamstudios" # delete this to disable disqus comments

[params]
    author = "Partho P. Das"
    description = "Software applications, services & training"
    githubUsername = "kitamstudios"
    accent = "#55acee"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    applicationInsights = "ce09371f-4ba9-4613-801f-f7fa48effc20"
    custom_css = ["css/main-override.css"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

# [[menu.main]]
#     url = "/post/"
#     name = "Posts"
#     weight = 3

# [[menu.main]]
#     url = "/project/"
#     name = "Projects"
#     weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:info@kitamstudios.com"
    name = "envelope-o"
    weight = 2

[[menu.icon]]
    url = "https://github.com/kitamstudios/"
    name = "github"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/company/kitamstudios"
    name = "linkedin"
    weight = 4
